block-command-path:
  - org.spigotmc
  - org.bukkit
  - com.sk89q
  - com.destroystokyo
  - co.aikar

block-command-path-whitelist:
  - plugins
  - plugin
  - pl
  - about
  - ?
  - help
  - version

block-command-name:
  - /
  - /desel
  - /deselect
  - /sel
  - /toggleplace
  - ;
  - list
  - me
  - msg
  - none
  - region
  - regions
  - rg
  - teammsg
  - tell
  - tm
  - toggleplace
  - trigger
  - w
  - we
  - worldedit