block-command-path:
  - org.spigotmc
  - org.bukkit
  - com.sk89q
  - com.destroystokyo
  - co.aikar
  - com.onarandombox
  - fr.neatmonster
  
block-command-send:
  - cronusquestbook
  - cronusquestlogs
  - cronusquestopen
  - cronusquestquit
  - cronusquestvisible

block-command-name:
  - br
  - brush
  - tool
  - /br
  - /brush
  - /
  - /desel
  - /deselect
  - /sel
  - /toggleplace
  - ;
  - list
  - me
  - msg
  - none
  - region
  - regions
  - rg
  - teammsg
  - tell
  - tm
  - toggleplace
  - trigger
  - w
  - we
  - worldedit